### ISSUE TITLE
Populate services.yaml

### ISSUE THREAD

**Issue by markgdev** [markgdev/home-assistant_OctopusAgile#17]
Populate services.yaml, currently it throws an error in the log as it’s not populated.

**Comment by markcocker** [comment]
Error in Configuration > Logs:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:263
First occurred: 17:36:15 (1 occurrences)
Last logged: 17:36:15
Unable to find services.yaml for the octopusagile integration 
```

**Comment by anthonyangel** [comment]
Based on https://github.com/home-assistant/core/issues/23197 we could just create an empty `services.yaml` file to silence this alert.

The services are set up in https://github.com/markgdev/home-assistant_OctopusAgile/blob/master/custom_components/OctopusAgile/__init__.py - but I'm not sure enough of what they all do to write accurate descriptions, 

```yaml
update_consumption:
  description: Get the most recent consumption data from the Octopus API

update_timers:
  description: Manually pull the pricing data for tomorrow

half_hour:
  description: ?
```
