### ISSUE TITLE
No attribute issues post installation

### ISSUE THREAD

**Issue by JustGav** [markgdev/home-assistant_OctopusAgile#99]
**Describe the bug**
Installed the plug in via HACS, configuration done in configuration YAML file.  Component does not seem to start or retrieve data.

**To Reproduce**
1. Install OctopusAgile via HACS
2. Edit configuration.yaml
```
octopusagile:
  region_code: "????"
  mpan: XXXXXX
  serial: XXXXXX
  auth: XXX
  startdate: "2022-10-24"
  gorate: 
  godayrate:
  gotimes:
  moneymakers:
  - switch.water_heater: null
  - climate.downstairs:
      params:
        temp: 25
sensor:
- platform: "octopusagile"
```
3. See error
 `Error setting up entry Name of the device for octopusagile
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
AttributeError: module 'custom_components.octopusagile' has no attribute 'async_setup_entry'`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/octopusagile/sensor.py", line 159, in update
    current_rate = self.hass.states.get("octopusagile.all_rates").attributes.get(rounded_time_str)
AttributeError: 'NoneType' object has no attribute 'attributes'`

**Expected behavior**
Sensor data should be populated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 106.0.5249.119

**Additional context**
Home Assistant Version : 2022.10.5

**Comment by JustGav** [comment]
![oa-1](https://user-images.githubusercontent.com/1734646/197506998-14c968ee-d038-4cb8-8301-2377d4ba6c73.jpg)
![oa-2](https://user-images.githubusercontent.com/1734646/197507087-7aaf7b3e-4998-4223-8f4d-649f1b1d2056.jpg)

**Comment by gsdevme** [comment]
I see the same issue. 

![Screenshot 2022-11-05 at 15 09 53](https://user-images.githubusercontent.com/319498/200126616-fc7db13a-1d3d-48eb-a074-1f72967a0698.png)

```yaml
octopusagile:
  region_code: "N"
  mpan: !secret electric_mpan
  serial: !secret electric_serial
  auth: !secret octopus_api_key
  agilerate: "AGILE-22-08-31"
  startdate: "2022-11-05"
  run_devices:
    - energy_time: 1.5
      entity_id: dishwasher
      run_before: "08:00:00"
      run_time: 3.0
```
